"""empty message

Revision ID: 3fc15a1067ba
Revises: 
Create Date: 2021-09-06 14:27:54.676616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc15a1067ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'tag',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('projects', 'advisor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'manager_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'director_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'projects', ['tag'])
    op.drop_constraint('projects_director_id_fkey', 'projects', type_='foreignkey')
    op.drop_constraint('projects_advisor_id_fkey', 'projects', type_='foreignkey')
    op.drop_constraint('projects_manager_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'employees', ['director_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'employees', ['advisor_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'employees', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_manager_id_fkey', 'projects', 'employees', ['manager_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('projects_advisor_id_fkey', 'projects', 'employees', ['advisor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('projects_director_id_fkey', 'projects', 'employees', ['director_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'projects', type_='unique')
    op.alter_column('projects', 'director_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'manager_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'advisor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'tag',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###
